# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  realease:
    runs-on: ubuntu-latest
    steps:
      - uses: RomanosTrechlis/actions-go-release@v1.0
        name: linux_x86 
        with:
          # Release's name
          release_name: linux_x86
          # Go's target operating system
          goos: linux
          # Go's target architecture
          goarch: amd64
      
      
