# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  realease:
    runs-on: ubuntu-latest
    steps:
      - uses: wangyoucao577/go-release-action@v1.38
        name: linux_x86
        with:
          # GITHUB_TOKEN for uploading releases to Github asserts.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # GOOS is the running programs operating system target: one of darwin, freebsd, linux, and so on.
          goos: linux # default is 
          # GOARCH is the running programs architecture target: one of 386, amd64, arm, s390x, loong64 and so on.
          goarch: amd64
          # Publish `.sha256` along with artifacts.
          sha256sum: TRUE # optional, default is FALSE
          # Upload binaries to specified release page that indicated by release name.
          release_name: linux_x86 # optional, default is 
          project_path: .
