name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  
  realease:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.38
        name: release linux/amd64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux 
          goarch: amd64
          compress_assets: FALSE
          asset_name: kvatyr-Linux-x86

      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.38
        name: release linux/amd64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: amd64
          compress_assets: FALSE
          asset_name: kvatyr-Mac-Intel
      
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.38
        name: release linux/amd64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: arm64
          compress_assets: FALSE
          asset_name: kvatyr-Mac-Apple-silicon
